import type { Metadata } from 'next';
import { ApolloProvider } from '@mockp/network/src/config/apollo';
import '@mockp/ui/src/app/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ApolloProvider>
        <body>{children}</body>
      </ApolloProvider>
    </html>
  );
}
