import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@mockp/ui/src/app/globals.css';
import { ApolloProvider } from '@mockp/network/src/config/apollo';
import { SessionProvider } from '@mockp/ui/src/components/molecules/SessionProvider';
import { Header } from '@mockp/ui/src/components/organisms/Header';
import { ToastContainer } from '@mockp/ui/src/components/molecules/Toast';
import { MenuItem } from '@mockp/util/types';
import { Container } from '@mockp/ui/src/components/atoms/Container';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Mockp',
  description: 'Generated by create next app',
};

const MENUITEMS: MenuItem[] = [
  { label: 'Search', href: '/search' },
  { label: 'Inquiries', href: '/bookings' },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SessionProvider>
        <ApolloProvider>
          <body className={`${inter.className} bg-gray-25`}>
            <Header menuItems={MENUITEMS} />
            <Container>{children}</Container>
            <ToastContainer />
          </body>
        </ApolloProvider>
      </SessionProvider>
    </html>
  );
}
