import type { Metadata } from 'next';
import { ApolloProvider } from '@mockp/network/src/config/apollo';
import '@mockp/ui/src/app/globals.css';
import { SessionProvider } from '@mockp/ui/src/components/molecules/SessionProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SessionProvider>
        <ApolloProvider>
          <body>{children}</body>
        </ApolloProvider>
      </SessionProvider>
    </html>
  );
}
