mutation RegisterWithCredentials(
  $registerWithCredentialsInput: RegisterWithCredentialsInput!
) {
  registerWithCredentials(
    registerWithCredentialsInput: $registerWithCredentialsInput
  ) {
    updatedAt
    uid
    name
    image
    createdAt
  }
}

query Brokerages(
  $distinct: [BrokerageScalarFieldEnum!]
  $orderBy: [BrokerageOrderByWithRelationInput!]
  $where: BrokerageWhereInput
  $cursor: BrokerageWhereUniqueInput
  $skip: Float
  $take: Float
) {
  brokerages(
    distinct: $distinct
    orderBy: $orderBy
    where: $where
    cursor: $cursor
    skip: $skip
    take: $take
  ) {
    createdAt
    description
    displayName
    properties {
      id
    }
    id
    brokerageManagers {
      uid
    }
    updatedAt
  }
}

mutation Login($loginInput: LoginInput!) {
  login(loginInput: $loginInput) {
    token
    user {
      uid
      name
      image
    }
  }
}

query GetAuthProvider($uid: String!) {
  getAuthProvider(uid: $uid) {
    uid
    type
  }
}

mutation RegisterWithProvider(
  $registerWithProviderInput: RegisterWithProviderInput!
) {
  registerWithProvider(registerWithProviderInput: $registerWithProviderInput) {
    uid
  }
}

query SearchProperties(
  $dateFilter: DateFilterInput!
  $locationFilter: LocationFilterInput!
  $featuresFilter: PropertyFeatureWhereInput
  $propertyFilter: PropertyFilter
) {
  searchProperties(
    dateFilter: $dateFilter
    locationFilter: $locationFilter
    featuresFilter: $featuresFilter
    propertyFilter: $propertyFilter
  ) {
    id
    address {
      lat
      lng
      address
    }
    images
    displayName
    listPrice
    featureCounts {
      type
      count
    }
    verification {
      verified
    }
  }
}

mutation CreatePropertyFeature($createPropertyFeatureInput: CreatePropertyFeatureInput!) {
  createPropertyFeature(createPropertyFeatureInput: $createPropertyFeatureInput) {
    id
  }
}

query myBrokerage {
  myBrokerage {
    id
    properties {
      displayName
      id
      description
      address {
        id
        address
        lat
        lng
      }
    }
    createdAt
    displayName
  }
}

mutation CreateBrokerage($createBrokerageInput: CreateBrokerageInput!) {
  createBrokerage(createBrokerageInput: $createBrokerageInput) {
    id
  }
}

query Properties(
  $skip: Float
  $take: Float
  $cursor: PropertyWhereUniqueInput
  $orderBy: [PropertyOrderByWithRelationInput!]
  $where: PropertyWhereInput
) {
  properties(
    skip: $skip
    take: $take
    cursor: $cursor
    orderBy: $orderBy
    where: $where
  ) {
    id
    displayName
    description
    images
    verification {
      verified
    }
    address {
      id
      lat
      lng
      address
    }
    featureCounts {
      type
      count
    }
  }

  propertiesCount(where: $where) {
    count
  }
}

mutation CreateProperty($createPropertyInput: CreatePropertyInput!) {
  createProperty(createPropertyInput: $createPropertyInput) {
    id
  }
}

fragment AgentFields on Agent {
  image
  uid
  displayName
}

fragment InquiryFields on Inquiry {
  id
  listPriceAtInquiry
  endTime
  startTime
  contactNotes
  passcode
  status
  inquiryTimeline {
    status
    timestamp
  }
  agentAssignment {
    assignedAgent {
      ...AgentFields
    }
  }
  property {
    displayName
    images
    address {
      address
      lat
      lng
    }
  }
}

query InquiriesForCustomer(
  $skip: Float
  $take: Float
  $cursor: InquiryWhereUniqueInput
  $orderBy: [InquiryOrderByWithRelationInput!]
  $where: InquiryWhereInput
  $distinct: [InquiryScalarFieldEnum!]
) {
  inquiriesForCustomer(
    skip: $skip
    take: $take
    cursor: $cursor
    orderBy: $orderBy
    where: $where
    distinct: $distinct
  ) {
    ...InquiryFields
  }

  inquiriesCount(where: $where) {
    count
  }
}

query InquiriesForProperty(
  $skip: Float
  $take: Float
  $cursor: InquiryWhereUniqueInput
  $orderBy: [InquiryOrderByWithRelationInput!]
  $where: InquiryWhereInput
  $distinct: [InquiryScalarFieldEnum!]
) {
  inquiriesForProperty(
    skip: $skip
    take: $take
    cursor: $cursor
    orderBy: $orderBy
    where: $where
    distinct: $distinct
  ) {
    ...InquiryFields
  }

  inquiriesCount(where: $where) {
    count
  }
}

mutation createInquiryTimeline(
  $createInquiryTimelineInput: CreateInquiryTimelineInput!
) {
  createInquiryTimeline(
    createInquiryTimelineInput: $createInquiryTimelineInput
  ) {
    inquiryId
    id
    managerId
    status
    timestamp
  }
}

query AgentMe {
  valetMe {
    uid
    brokerageId
  }
}

query AdminMe {
  adminMe {
    uid
  }
}

mutation CreateAgent($createAgentInput: CreateAgentInput!) {
  createAgent(createAgentInput: $createAgentInput) {
    agent {
      uid
      displayName
      licenseID
      image
      brokerageId
    }
    email
    temporaryPassword
  }
}

query myPropertiesAsAgent($skip: Float, $take: Float) {
  myPropertiesAsAgent(skip: $skip, take: $take) {
    id
    displayName
    description
    images
    verification {
      verified
    }
    address {
      id
      lat
      lng
      address
    }
    featureCounts {
      type
      count
    }
  }
  myPropertiesAsAgentCount {
    count
  }
}

query companyAgents(
  $distinct: [AgentScalarFieldEnum!]
  $skip: Float
  $take: Float
  $cursor: AgentWhereUniqueInput
  $orderBy: [AgentOrderByWithRelationInput!]
  $where: AgentWhereInput
) {
  companyAgents(
    distinct: $distinct
    skip: $skip
    take: $take
    cursor: $cursor
    orderBy: $orderBy
    where: $where
  ) {
    displayName
    uid
    createdAt
    updatedAt
    brokerageId
    image
    licenseID
  }

  companyAgentsTotal(where: $where)
}

query valetPickups($skip: Float, $take: Float) {
  valetPickups(skip: $skip, take: $take) {
    id
    contactNotes
    agentAssignment {
      visitLat
      visitLng
      assignedAgentId
    }
    startTime
    endTime
    property {
      address {
        lat
        lng
      }
    }
  }
  valetPickupsTotal
}

query valetDrops($skip: Float, $take: Float) {
  valetDrops(skip: $skip, take: $take) {
    id
    contactNotes
    startTime
    endTime
    agentAssignment {
      visitLat
      visitLng
      assignedAgentId
    }
    property {
      address {
        lat
        lng
      }
    }
  }
  valetDropsTotal
}

mutation AssignAgent($inquiryId: Float!, $status: String!) {
  assignAgent(inquiryId: $inquiryId, status: $status) {
    id
  }
}

fragment AgentInquiryFields on Inquiry {
  id
  contactNotes
  passcode
  status
  startTime
  endTime
  property {
    address {
      lat
      lng
    }
  }
}

query myPickupTrips(
  $distinct: [InquiryScalarFieldEnum!]
  $skip: Float
  $take: Float
  $orderBy: [InquiryOrderByWithRelationInput!]
  $where: InquiryWhereInput
) {
  inquiriesForAgent(
    distinct: $distinct
    skip: $skip
    take: $take
    orderBy: $orderBy
    where: $where
  ) {
    ...AgentInquiryFields
    agentAssignment {
      visitLat
      visitLng
      assignedAgentId
    }
  }
  inquiriesCount(where: $where) {
    count
  }
}
query myDropTrips(
  $distinct: [InquiryScalarFieldEnum!]
  $skip: Float
  $take: Float
  $orderBy: [InquiryOrderByWithRelationInput!]
  $where: InquiryWhereInput
) {
  inquiriesForAgent(
    distinct: $distinct
    skip: $skip
    take: $take
    orderBy: $orderBy
    where: $where
  ) {
    ...AgentInquiryFields
    agentAssignment {
      visitLat
      visitLng
      assignedAgentId
    }
  }
  inquiriesCount(where: $where) {
    count
  }
}

mutation CreateVerification(
  $createVerificationInput: CreateVerificationInput!
) {
  createVerification(createVerificationInput: $createVerificationInput) {
    adminId
    createdAt
    propertyId
    updatedAt
    verified
  }
}

mutation RemoveVerification($where: VerificationWhereUniqueInput!) {
  removeVerification(where: $where) {
    adminId
    createdAt
    propertyId
    updatedAt
    verified
  }
}

query admins(
  $distinct: [AdminScalarFieldEnum!]
  $skip: Float
  $take: Float
  $cursor: AdminWhereUniqueInput
  $orderBy: [AdminOrderByWithRelationInput!]
  $where: AdminWhereInput
) {
  admins(
    distinct: $distinct
    skip: $skip
    take: $take
    cursor: $cursor
    orderBy: $orderBy
    where: $where
  ) {
    uid
    updatedAt
    user {
      name
    }
    createdAt
    verificationsCount
  }
  adminsCount(where: $where)
}

mutation RemoveAdmin($where: AdminWhereUniqueInput!) {
  removeAdmin(where: $where) {
    createdAt
    user {
      name
    }
    updatedAt
    uid
  }
}

mutation CreateAdmin($createAdminInput: CreateAdminInput!) {
  createAdmin(createAdminInput: $createAdminInput) {
    createdAt
    user {
      name
    }
    uid
    updatedAt
  }
}