import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@mockp/ui/src/app/globals.css';
import { MenuItem } from '@mockp/util/types';
import { ApolloProvider } from '@mockp/network/src/config/apollo';
import { SessionProvider } from '@mockp/ui/src/components/molecules/SessionProvider';
import { ToastContainer } from '@mockp/ui/src/components/molecules/Toast';
import { Container } from '@mockp/ui/src/components/atoms/Container';
import { Header } from '@mockp/ui/src/components/organisms/Header';
import {
  getMessages,
  I18nProvider,
  LOCALE_COOKIE_KEY,
  resolveLocale,
} from '@mockp/util/i18n';
import { cookies } from 'next/headers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Mockp | Admin',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = resolveLocale(cookies().get(LOCALE_COOKIE_KEY)?.value);
  const menuMessages = getMessages(locale).menu;
  const menuItems: MenuItem[] = [
    { label: menuMessages.properties, href: '/' },
    { label: menuMessages.verifications, href: '/verifications' },
    { label: menuMessages.admins, href: '/manageAdmins' },
  ];

  return (
    <html lang={locale}>
      <body className={`${inter.className} bg-gray-25`}>
        <SessionProvider>
          <ApolloProvider>
            <I18nProvider initialLocale={locale}>
              <Header type="admin" menuItems={menuItems} />
              <Container>{children}</Container>
            </I18nProvider>
          </ApolloProvider>
        </SessionProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
